name: "Check"

on:
  push:
    branches: main
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        runner:
          - macos-12
          - ubuntu-22.04
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: Check
      run: nix flake check ./main
