name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        runner:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Check
        # Build parallelism is reduced here to increase probability of build success.
        # This decision is influenced by the opinion that the speed of CI is not very
        # important for this repository.
        run: nix flake check ./main --max-jobs 1
