name: CI

permissions:
  contents: read

on:
  push:
    branches: main
  pull_request:

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          matrix="$(nix eval --accept-flake-config --json './main#githubActions.matrix')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
  check:
    needs: nix-matrix
    strategy:
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: freckle
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Check
        run: nix build --accept-flake-config --print-build-logs --keep-going --impure "./main#${{ matrix.attr }}"
        env:
          NIXPKGS_ALLOW_INSECURE: "1"
