name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: freckle
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Check
        run: nix flake check --accept-flake-config ./main
