name: Update flake inputs

on:
  schedule:
    - cron: "0 0 * * 6"

defaults:
  run:
    working-directory: main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - name: Update
        run: nix flake update

      # Use a PAT so that Workflows run on the created PR
      - id: token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.FRECKLE_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.FRECKLE_AUTOMATION_PRIVATE_KEY }}

      - uses: peter-evans/create-pull-request@v6
        with:
          branch: gh/update
          title: Update flake inputs
          body: |
            Automatic run of `nix flake update`.
          token: ${{ steps.token.outputs.token }}
